name: Deploy to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest test.py -v || echo "Tests completed"
        
    - name: Lint with flake8
      run: |
        pip install flake8
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Navigate to project directory
          cd /home/ec2-user/llm-infer-stress
          
          # Stop running services
          pkill -f "python3 app.py" || true
          pkill -f "python3 health.py" || true
          
          # Pull latest changes
          git pull origin main
          
          # Install/update dependencies
          pip3 install -r requirements.txt
          
          # Start services
          nohup python3 app.py > app.log 2>&1 &
          nohup python3 health.py > health.log 2>&1 &
          
          # Wait a moment and check if services started
          sleep 5
          ps aux | grep python3 | grep -E "(app\.py|health\.py)"
          
          echo "Deployment completed successfully!" 