[server]
headless = true
port = 8501
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
allowRunOnSave = false
runOnSave = false
baseUrlPath = ""

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[global]
developmentMode = false

[theme]
base = "dark"

# Force disable WebSockets - use HTTP polling instead
[client]
toolbarMode = "minimal"
showErrorDetails = false

[runner]
magicEnabled = false
installTracer = false 